### ISSUE TITLE
Use PHP v5.5.9 instead of v5.6 

### ISSUE THREAD

**Issue by brunocascio** [browner12/helpers#1]
Is it possible? 

Laravel 5.2 requires PHP >= 5.5.9, and this package brokes these requirements :/

**Comment by browner12** [comment]
I'm leaning towards no since 5.5 will be EOL in 3 months. are you on shared hosting that you can't get upgraded?

**Comment by brunocascio** [comment]
Good. No, I'm using [Laradock](https://github.com/LaraDock/laradock) that uses PHP 5.5.9 and your library is the only one that uses PHP 5.6 (in my app).
I have to fork Laradock and modify the Dockerfile to support PHP 5.6, but if your library supports php 5.5.9, would be awesome :D

**Comment by browner12** [comment]
sorry for the delay @brunocascio, i finally broke down.

https://github.com/browner12/helpers/pull/4

pushing a release soon
