### ISSUE TITLE
php artisan make:helper MyHelper show problem

### ISSUE THREAD

**Issue by king52311** [browner12/helpers#11]
`php artisan make:helper MyHelper
`
do last step show problem:
`[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "make:helper" is not defined.
  Did you mean one of these?
      make:auth
      make:command
      make:controller
      make:event
      make:job
      make:listener
      make:mail
      make:middleware
      make:migration
      make:model
      make:notification
      make:policy
      make:provider
      make:request
      make:seeder
      make:test`

**Comment by browner12** [comment]
did you register the service provider? if you register the service provider it will register the command for you automatically.

if you type `php artisan`, do you see `make:helper` listed?

**Comment by king52311** [comment]
\app\Providers\AppServiceProvider.php 
` public function register()
    {
        $this->app->register(\browner12\helpers\HelperServiceProvider::class);
        //
    }`
is ok!
because not found this code in your document, thought not configured here,think you!
