### ISSUE TITLE
Unable to override laravel helper functions 

### ISSUE THREAD

**Issue by delmicio** [browner12/helpers#19]
I'm trying to override a default laravel helper (logger) but is not working.
```PHP
if (!function_exists('logger')) {
    function logger($message = null, array $context = [])
    {
        if (is_null($message)) {
            return app('log');
        } 

        return app('log')->debug('test', $context);
    }
}
```

Is there a way to make this work?

**Comment by browner12** [comment]
take out the first line. the function already exists

**Comment by delmicio** [comment]
I've tried that, it throws a FatalErrorException

> Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
> Cannot redeclare logger() (previously declared in /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:514)

**Comment by browner12** [comment]
looks like PHP doesn't allow you to override functions, so you'll have to rename it.
