### ISSUE TITLE
5.7 Compatibility 

### ISSUE THREAD

**Issue by Riversedgedesigns** [browner12/helpers#20]
First let me say love great project. Very easy and useful.

With a quick look at [https://laravel.com/docs/5.7/releases#laravel-5.7](url) I dont think this project is effected by the latest version. If I had more free time I would verify by testing it myself.

If everything is good, can we get a bump on the version?

**Comment by browner12** [comment]
sure thing. i'll get to it tomorrow. thanks for reminding me.

**Comment by browner12** [comment]
fixed with newest release.  thanks again for the reminder.

https://github.com/browner12/helpers/releases/tag/v2.1.3
