### ISSUE TITLE
Helpers is not defined in server hosting

### ISSUE THREAD

**Issue by sukmadana** [browner12/helpers#23]
hello,
please help me the helpers are not defined after I upload it to the hosting server. 
![screenshot 2](https://user-images.githubusercontent.com/33949519/46460686-4398d200-c7ef-11e8-972b-b333286a0d99.png)

please help me about this issue!

**Comment by browner12** [comment]
You'll need to provide me more information about your setup.

- Did you run `composer install browner12/helpers`?
- Did you publish the assets? `php artisan vendor:publish`
- Did you make a new file for this helper? `php artisan make:helper SettingHelper` or something similar?
- If you did make this file, what does it look like?
- What does `config/helpers.php` look like?

**Comment by aelfannir** [comment]
Same here, 

```php
'custom_helpers' => [ "hello" ],
```
**app/Helpers/MyHelper.php**
```php
if (!function_exists('hello')) {

    /**
     * say hello
     *
     * @param string $name
     * @return string
     */
    function hello($name)
    {
        return 'Hello ' . $name . '!';
    }
}
```

**web.php**
```php
Route::get('/', function () {
    return hello("somename");
});
```

> Call to undefined function hello()

**Comment by aelfannir** [comment]
It works only when i put the helper in the composer.json
```json
"autoload": {
        ...
        "files": [
            "app/Helpers/MyHelpes.php"
        ]
```

**Comment by aelfannir** [comment]
I created a new file **includes.php** in Helper directory, then i added it to **autoload's files**

**includes.php**
```php
<?php

$files = glob(__DIR__ . '/*.php');
if ($files === false) {
    throw new RuntimeException("Failed to glob for function files");
}
foreach ($files as $file) {
    require_once $file;
}
unset($file);
unset($files);
```

**Comment by browner12** [comment]
Do you have Laravel autodiscovery on or off?  If it's off, make sure you register the Service Provider.

```php
'providers' => [
    browner12\helpers\HelperServiceProvider::class,
];
```
