### ISSUE TITLE
Is it compatible with laravel 5.3?

### ISSUE THREAD

**Issue by Kyosfonica** [browner12/helpers#6]
`php artisan vendor:publish --provider="browner12\helpers\HelperServiceProvider"` This command returns that there is nothing to publish.
`php artisan make:helper MyHelper` This command returns an error that artisan doesn't have helper as an action.

Thanks

**Comment by Kyosfonica** [comment]
Solved. The issue was that the service provider was registered at the bottom of the providers array. It seems that there it shoudn't be placed.
Now it works fine.

**Comment by browner12** [comment]
glad it worked for you.
